language: php

php:
  - 7.2
  - 7.3
  - 7.4

branches:
  only:
    - develop

cache:
  directories:
    - source/app/vendor
    - $HOME/.composer/cache

before_script:
  - cd $HOME/source/app
  - composer self-update

install:
  - cd $HOME/source/app
  - composer install --prefer-dist --no-progress --no-suggest --no-interaction

script:
  - cd $HOME/source/app
  - ./vendor/bin/phpunit;