language: php

php:
  - 7.2
  - 7.3
  - 7.4

branches:
  only:
    - develop

cache:
  directories:
    - source/app/vendor
    - $HOME/.composer/cache

env:
  - APP_DB_HOST=xxx APP_DB_NAME=xxx APP_DB_USER=xxx APP_DB_PASS=xxx APP_DB_DNS=mysql:host=${APP_DB_HOST};dbname=${APP_DB_NAME} APP_SLAVE_DB_HOSTS=xxx

before_install:
  - composer self-update

install:
  - cd source/app
  - composer install --prefer-dist --no-progress --no-suggest --no-interaction

script:
  - ./vendor/bin/phpunit;

jobs:
  fast_finish: true
  include:
    - stage: Test
      name: Lowest dependencies
      php: 7.2
      install:
        - cd source/app
        - composer update --prefer-dist --prefer-lowest

    - stage: Code Quality
      name: Code coverage
      php: 7.2
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - cd source/app
        - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover;

    - stage: Code Quality
      name: Static analysis
      php: 7.2
      install:
        - cd source/app
        - composer require --dev phpstan/phpstan ^0.12 vimeo/psalm ^3.11 phpmetrics/phpmetrics ^2.6;
      script:
        - ./vendor/bin/phpstan analyse -c phpstan.neon --no-progress --no-interaction;
        - ./vendor/bin/psalm --show-info=false
        - ./vendor/bin/phpmetrics --exclude=Exception src

    - stage: Code Quality
      name: Coding standards
      php: 7.2
      install:
        - cd source/app
        - composer require --dev friendsofphp/php-cs-fixer ^2.0;
      script:
        - ./vendor/bin/php-cs-fixer --dry-run -v fix;