language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update

install:
  - composer install --prefer-dist --no-progress --no-suggest --no-interaction

script:
  - ./vendor/bin/phpunit;