version: '3'

services:
  app:
    image: ghcr.io/buddying-inc/buddying-php:amazonlinux2-apache24-php72
    container_name: bear-app
    working_dir: /var/www/vhosts/bear
    volumes:
      - bear-source:/var/www/vhosts/bear:rw
      - ./vhosts.conf:/etc/httpd/conf.d/vhosts.conf
    ports:
      - '80:80'
    depends_on:
      - db
    environment:
      - PHP_XDEBUG=off
      - COMPOSER_ALLOW_SUPERUSER=1

  db:
    image: ghcr.io/buddying-inc/buddying-mysql57:latest
    container_name: bear-db
    volumes:
      - ./.db:/var/lib/mysql:delegated
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=bear_db
      - MYSQL_USER=bear
      - MYSQL_PASSWORD=passw0rd
      - TZ=Asia/Tokyo

volumes:
  bear-source:
    external: true
